# Generated by Django 3.0.3 on 2020-04-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mdp',
            field=models.CharField(default='mdp', max_length=20),
            preserve_default=False,
        ),
    ]
