# Generated by Django 3.0.3 on 2020-04-06 12:11

import administrateur.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accueil', '0002_customuser_mdp'),
    ]

    operations = [
        migrations.CreateModel(
            name='formulaire',
            fields=[
                ('id', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cin', models.CharField(default='', max_length=8, unique=True)),
                ('nom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=25)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('phone', models.IntegerField(default='')),
                ('adresse', models.CharField(max_length=1000)),
                ('date_naissance', models.DateField(verbose_name=False)),
                ('encadrant1', models.CharField(max_length=25)),
                ('encadrant2', models.CharField(max_length=25)),
                ('encadrant3', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='offres',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('deadline', models.DateField(verbose_name=False)),
            ],
        ),
        migrations.CreateModel(
            name='diplome',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='administrateur.formulaire')),
                ('attestation_bac', models.FileField(upload_to=administrateur.models.user_directory_path)),
                ('attestation_licence', models.FileField(upload_to=administrateur.models.user_directory_path)),
                ('attestation_master', models.FileField(upload_to=administrateur.models.user_directory_path)),
                ('attestation_doc', models.FileField(upload_to=administrateur.models.user_directory_path)),
                ('these_doc', models.FileField(upload_to=administrateur.models.user_directory_path)),
                ('article_doc', models.FileField(upload_to=administrateur.models.user_directory_path)),
                ('cv', models.FileField(upload_to=administrateur.models.user_directory_path)),
                ('lettre_motivation', models.FileField(upload_to=administrateur.models.user_directory_path)),
            ],
        ),
    ]
