# Generated by Django 3.0.3 on 2020-04-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0002_auto_20200407_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaire',
            name='encadrant1',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='encadrant2',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='formulaire',
            name='encadrant3',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
