# Generated by Django 3.0.3 on 2020-04-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0003_auto_20200411_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offres',
            name='deadline',
        ),
    ]
